GET http://localhost:3000/products

###
GET http://localhost:3000/products/2

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 100
}

###
PATCH http://localhost:3000/products/1
Content-Type: application/json

{
    "name": "Product changed",
    "price": 150
}

###
DELETE http://localhost:3000/products/3

###
GET http://localhost:3000/stock-inputs/1

###
POST http://localhost:3000/stock-inputs
Content-Type: application/json

{
    "product_id": 2,
    "quantity": 10,
    "date": "2000-01-01"
}

###
GET http://localhost:3000/stock-outputs/1

###
POST http://localhost:3000/stock-outputs
Content-Type: application/json

{
    "product_id": 2,
    "quantity": 10,
    "date": "2000-01-01"
}